{
 "title": "Data Dashboard",
 "tags": [ "rayVersion:2.49.1" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "query_result(count by (SessionName)(last_over_time(ray_data_output_bytes{}[$__range])))"
    }
   },
   {
    "name": "DatasetID",
    "query": {
     "query": "query_result(count by (dataset)(last_over_time(ray_data_output_bytes{SessionName=~\"$SessionName\",}[$__range])))"
    }
   },
   {
    "name": "Operator",
    "query": {
     "query": "query_result(count by (operator)(last_over_time(ray_data_output_bytes{SessionName=~\"$SessionName\",}[$__range])))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Spilled",
   "type": "graph",
   "description": "Amount spilled by dataset operators. DataContext.enable_get_object_locations_for_metrics must be set to True to report this metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_spilled_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Spilled: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Freed",
   "type": "graph",
   "description": "Amount freed by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_freed_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Freed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Amount of memory store used by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_current_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Current Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "CPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "GPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Output / Second",
   "type": "graph",
   "description": "Bytes output per second by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_output_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Output / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Max Bytes to Read",
   "type": "graph",
   "description": "Maximum bytes to read from streaming generator buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_max_bytes_to_read{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Max Bytes to Read: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Throughput (Rows Output / Second)",
   "type": "graph",
   "description": "Total rows output per second by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "rows/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_output_rows{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Rows Output / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Blocks Received by Operator / Second",
   "type": "graph",
   "description": "Number of input blocks received by operator per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "blocks/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Blocks Received / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Bytes Received by Operator / Second",
   "type": "graph",
   "description": "Byte size of input blocks received by operator per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_inputs_received{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Received / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Blocks Processed by Tasks / Second",
   "type": "graph",
   "description": "Number of input blocks that operator's tasks have finished processing per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "blocks/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Blocks Processed / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Bytes Processed by Tasks / Second",
   "type": "graph",
   "description": "Byte size of input blocks that operator's tasks have finished processing per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_task_inputs_processed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Processed / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Input Bytes Submitted to Tasks / Second",
   "type": "graph",
   "description": "Byte size of input blocks passed to submitted tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_inputs_of_submitted_tasks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Submitted / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Blocks Generated by Tasks / Second",
   "type": "graph",
   "description": "Number of output blocks generated by tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "blocks/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Blocks Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Generated by Tasks / Second",
   "type": "graph",
   "description": "Byte size of output blocks generated by tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Average Bytes Generated / Output Block",
   "type": "graph",
   "description": "Average byte size of output blocks generated by tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(ray_data_bytes_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m]) / increase(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m])",
     "legendFormat": "Average Bytes Generated / Output Block: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Average Number of Output Blocks / Task",
   "type": "graph",
   "description": "Average number of output blocks generated by tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "increase(ray_data_num_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m])",
     "legendFormat": "Average Number of Output Blocks / Task: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Generated by Tasks / Second",
   "type": "graph",
   "description": "Number of rows in generated output blocks from finished tasks per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "rows/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_rows_task_outputs_generated{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Rows Generated / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Output Blocks Taken by Downstream Operators / Second",
   "type": "graph",
   "description": "Number of output blocks taken by downstream operators per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "blocks/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Blocks Taken / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Output Bytes Taken by Downstream Operators / Second",
   "type": "graph",
   "description": "Byte size of output blocks taken by downstream operators per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_outputs_taken{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[1m])) by (dataset, operator)",
     "legendFormat": "Bytes Taken / Second: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Output Bytes from Finished Tasks / Second (by Node)",
   "type": "graph",
   "description": "Byte size of output blocks from finished tasks per second, grouped by node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_bytes_outputs_of_finished_tasks_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}[1m])) by (dataset, node_ip)",
     "legendFormat": "Bytes output / Second: {{dataset}}, {{node_ip}}"
    }
   ]
  },
  {
   "title": "Blocks from Finished Tasks / Second (by Node)",
   "type": "graph",
   "description": "Number of output blocks from finished tasks per second, grouped by node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "blocks/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_blocks_outputs_of_finished_tasks_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}[1m])) by (dataset, node_ip)",
     "legendFormat": "Blocks output / Second: {{dataset}}, {{node_ip}}"
    }
   ]
  },
  {
   "title": "Submitted Tasks",
   "type": "graph",
   "description": "Number of submitted tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_submitted{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Submitted Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "description": "Number of running tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_running{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Running Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Tasks with output blocks",
   "type": "graph",
   "description": "Number of tasks that already have output.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_have_outputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Tasks with output blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Finished Tasks",
   "type": "graph",
   "description": "Number of finished tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Finished Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Throughput (by Node)",
   "type": "graph",
   "description": "Number of finished tasks per second, grouped by node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "tasks/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_data_num_tasks_finished_per_node{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}[1m])) by (dataset, node_ip)",
     "legendFormat": "Finished Tasks: {{dataset}}, {{node_ip}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "graph",
   "description": "Number of failed tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_tasks_failed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Failed Tasks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Block Generation Time",
   "type": "graph",
   "description": "Time spent generating blocks in tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_block_generation_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Block Generation Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Submission Backpressure Time",
   "type": "graph",
   "description": "Time spent in task submission backpressure.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_task_submission_backpressure_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Backpressure Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Completion Time",
   "type": "graph",
   "description": "Time spent running tasks to completion w/ backpressure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "increase(ray_data_task_completion_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m])",
     "legendFormat": "Task Completion Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Output Backpressure Time",
   "type": "graph",
   "description": "Time spent in output backpressure.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "increase(ray_data_task_output_backpressure_time{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m])",
     "legendFormat": "Task Output Backpressure Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Task Completion Time Without Backpressure",
   "type": "graph",
   "description": "Time spent running tasks to completion w/o backpressure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "increase(ray_data_task_completion_time_without_backpressure{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m]) / increase(ray_data_num_tasks_finished{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}[5m])",
     "legendFormat": "Task Completion Time w/o Backpressure: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Inqueue Size (Blocks)",
   "type": "graph",
   "description": "Number of blocks in operator's internal input queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_inqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Inqueue Size (Bytes)",
   "type": "graph",
   "description": "Byte size of input blocks in the operator's internal input queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_inqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Outqueue Size (Blocks)",
   "type": "graph",
   "description": "Number of blocks in operator's internal output queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_outqueue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator Internal Outqueue Size (Bytes)",
   "type": "graph",
   "description": "Byte size of output blocks in the operator's internal output queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_internal_outqueue{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator External OutQueue Size (Blocks)",
   "type": "graph",
   "description": "Number of blocks in operator's external output queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_output_queue_blocks{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Number of Blocks: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Operator External OutQueue Size (bytes)",
   "type": "graph",
   "description": "Byte size of blocks in operator's external output queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_num_output_queue_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Number of Bytes: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Size of Blocks used in Pending Tasks (Bytes)",
   "type": "graph",
   "description": "Byte size of input blocks used by pending tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_pending_task_inputs{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Freed Memory in Object Store (Bytes)",
   "type": "graph",
   "description": "Byte size of freed memory in object store.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_freed{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Spilled Memory in Object Store (Bytes)",
   "type": "graph",
   "description": "Byte size of spilled memory in object store.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_obj_store_mem_spilled{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Bytes Size: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Iteration Initialization Time",
   "type": "graph",
   "description": "Seconds spent in iterator initialization code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_initialize_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Iteration Blocked Time",
   "type": "graph",
   "description": "Seconds user thread is blocked by iter_batches()",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_total_blocked_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Iteration User Time",
   "type": "graph",
   "description": "Seconds spent in user code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_user_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Scheduling Loop Duration",
   "type": "graph",
   "description": "Duration of the scheduling loop in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_sched_loop_duration_s{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",}) by (dataset)",
     "legendFormat": "Scheduling Loop Duration: {{dataset}}"
    }
   ]
  },
  {
   "title": "Budget (CPU)",
   "type": "graph",
   "description": "Budget (CPU) for the operator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_cpu_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Budget (CPU): {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Budget (GPU)",
   "type": "graph",
   "description": "Budget (GPU) for the operator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "gpu" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_gpu_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Budget (GPU): {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Budget (Memory)",
   "type": "graph",
   "description": "Budget (Memory) for the operator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_memory_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Budget (Memory): {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Budget (Object Store Memory)",
   "type": "graph",
   "description": "Budget (Object Store Memory) for the operator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_object_store_memory_budget{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",ray_io_cluster=~\"$Cluster\",, operator=~\"$Operator\"}) by (dataset, operator)",
     "legendFormat": "Budget (Object Store Memory): {{dataset}}, {{operator}}"
    }
   ]
  }
 ]
}